var config={};
config.NAME="CLIENTNAME";
config.SECRET="SECRET";
config.URL="SERVERURL";
config.OUTPUTDIR="DIRECTORY WHERE OUTPUT FROM SERVER SHOULD APPEAR";
config.INPUTDIR="DIRECTORY WHERE INPUT TO THE SERVER FROM THE CLIENT SHOULD APPEAR";
